# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51d15e5e08916ef28b5515e4621ddaac6e3e467951cb92487b6ae7f10830c38dc4619ba7ee830695bc6e7a87a6c5e3840006b7fd6a1de69c2bb9ad0ccb158684

test:
  secret_key_base: 5a48b7c5b3777b78b06d62ecab3832960c4ac84ee9ed8f46c9ba484f08fb48b91be0666e8ec514189293c3b1370650aab80a7d82ba39db428396c684cad3aa66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
